#
# Create interface IP configuration, change hostname, enable LLDP
#
---
- name: Create configuration directory
  local_action: file path={{configs}} state=directory
  run_once: true
  check_mode: no
  changed_when: no

- name: Create configurations
  template: src=../{{ansible_network_os}}/interface-config.j2 dest={{configs}}/{{inventory_hostname}}.if.cfg
  check_mode: no
