---
- name: Prepare for configuration build
  hosts: localhost
  tasks:
  - shell: |
      mkdir -p {{config_dir}}
      rm -fr {{build_dir}}
      mkdir -p {{build_dir}}
      cd {{build_dir}}
      mkdir {{groups['all']|join(' ')}}
    args:
      warn: false
    changed_when: false

- name: Generate configs
  hosts: all
  connection: local
  roles:
    - routing
    - base
    - dmvpn
  tasks:
  - include_role:
      name: "{{ simulation|default('virl') }}"

- name: Assemble configurations
  hosts: all
  connection: local
  tasks:
  - assemble:
      src: "{{build_dir}}/{{inventory_hostname}}"
      dest: "{{config_dir}}/{{inventory_hostname}}.conf"
      ignore_hidden: yes
    check_mode: no
