---
- name: Copy and deploy configurations
  hosts: all
  tasks:
  - name: Enable SCP server and configuration archive
    ios_config:
      src: deploy_setup.cfg
    become: yes
    tags: [ copy,deploy ]

  - block:
    - stat: path={{config_dir}}/{{inventory_hostname}}.conf
      register: stat
    - assert:
        that: stat.stat.exists
        msg:  "Cannot find router configuration file for {{inventory_hostname}}"
    - name: Copy candidate configuration into routers
      net_put:
        src: "{{config_dir}}/{{inventory_hostname}}.conf"
        dest: "flash:candidate.cfg"
    tags: [ copy ]

  - block:
    - cli_command:
        command: disable
    - name: Enter Enable mode
      cli_command:
        command: enable
        prompt: Password
        answer: "{{ ansible_become_password|default(ansible_ssh_pass) }}"
    - name: Replace configuration
      cli_command:
        command: configure replace flash:candidate.cfg force revert trigger timer 120
      register: replace
      tags: [ print_action ]
      vars:
        ansible_command_timeout: 240
    - name: Confirm configuration replace
      cli_command:
        command: configure confirm

    - file: path={{build_dir}}/results state=directory
      check_mode: no
    - name: Save configuration replace results
      copy:
        content: |

          *********************************
          Results on {{inventory_hostname}}
          *********************************

          {{replace.stdout}}
        dest: "{{build_dir}}/results/{{inventory_hostname}}.txt"
      delegate_to: localhost
    - name: Assemble final report
      assemble: src={{build_dir}}/results dest={{build_dir}}/results.txt
      run_once: true
      delegate_to: localhost
    tags: [ deploy ]
