---
- hosts: all
  name: Create and read node data model
  tasks:
  - include_vars: "{{item}}"
    run_once: true
    with_first_found:
    - "{{inventory_dir}}/{{model|default('fabric.yml')}}"
    - "fabric.yml"
    tags: [ model ]
  - name: Create per-node data model from fabric data model
    template: src=model/fabric-to-nodes.j2 dest=nodes.yml
    run_once: true
    tags: [ model ]
  - include_vars: "nodes.yml"
    tags: [ always ]

- hosts: all
  name: Configure LLDP on fabric devices
  tags: [ config ]
  tasks:
  - include_tasks: "{{ansible_network_os}}/deploy_lldp.yml"
  - name: Set 'wait for LLDP flag'
    set_fact: wait_flag=1

- hosts: all
  name: Validate fabric connectivity using LLDP neighbors
  tags: [ validate ]
  tasks:
  - name: Wait for LLDP to start
    include_tasks: lldp/wait.yml
  - name: Gather LLDP facts
    include_tasks: "{{item}}"
    with_first_found:
      - "{{ansible_network_os}}/lldp_facts.yml"
      - "lldp/napalm_lldp_facts.yml"
  - name: Validate fabric connectivity using LLDP neighbors
    include_tasks: lldp/validate.yml
